### ISSUE TITLE
Package submitted to Bioconductor

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/CTdata#12]
See [issue 2986](https://github.com/Bioconductor/Contributions/issues/2986).

**Comment by lgatto** [comment]
The package [has been accepted](https://github.com/Bioconductor/Contributions/issues/2986#issuecomment-1495973917).

**Comment by JulieDevis** [comment]
The package [has been published](https://bioconductor.org/packages/release/bioc/html/CTdata.html).
